name: Publish Workshops

on:
  push:
    branches:
      - aws-workshops

jobs:
  build-deploy:
    runs-on: [self-hosted, public, linux, x64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - run: |
              git fetch --no-recurse-submodules origin azure-workshops
              git merge origin/azure-workshops
      - name: Hugo to GH Pages
        uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PAGES_TOKEN }}
          cname: workshop.bridgecrew.io 
          args: -d aws
