name: Publish Workshops

on:
  push:
    branches:
      - aws-workshops

jobs:
  build-deploy:
    runs-on: [self-hosted, public, linux, x64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Merge Azure Content
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: azure-workshops
          target_branch: aws-workshops
          github_token: ${{ github.token }}
      - name: Hugo to GH Pages
        uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PAGES_TOKEN }}
          cname: workshop.bridgecrew.io 
          args: -d aws
